In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("city_day.csv")

In [3]:
df

City        Date  PM2.5   PM10     NO    NO2    NOx    NH3  \
0          Ahmedabad  2015-01-01    NaN    NaN   0.92  18.22  17.15    NaN   
1          Ahmedabad  2015-01-02    NaN    NaN   0.97  15.69  16.46    NaN   
2          Ahmedabad  2015-01-03    NaN    NaN  17.40  19.30  29.70    NaN   
3          Ahmedabad  2015-01-04    NaN    NaN   1.70  18.48  17.97    NaN   
4          Ahmedabad  2015-01-05    NaN    NaN  22.10  21.42  37.76    NaN   
...              ...         ...    ...    ...    ...    ...    ...    ...   
29526  Visakhapatnam  2020-06-27  15.02  50.94   7.68  25.06  19.54  12.47   
29527  Visakhapatnam  2020-06-28  24.38  74.09   3.42  26.06  16.53  11.99   
29528  Visakhapatnam  2020-06-29  22.91  65.73   3.45  29.53  18.33  10.71   
29529  Visakhapatnam  2020-06-30  16.64  49.97   4.05  29.26  18.80  10.03   
29530  Visakhapatnam  2020-07-01  15.00  66.00   0.40  26.85  14.05   5.20   

          CO    SO2      O3  Benzene  Toluene  Xylene   AQI    AQI_Bucket  
0       0.92  27.64  133.36     0.00     0.02    0.00   NaN           NaN  
1       0.97  24.55   34.06     3.68     5.50    3.77   NaN           NaN  
2      17.40  29.07   30.70     6.80    16.40    2.25   NaN           NaN  
3       1.70  18.59   36.08     4.43    10.14    1.00   NaN           NaN  
4      22.10  39.33   39.31     7.01    18.89    2.78   NaN           NaN  
...      ...    ...     ...      ...      ...     ...   ...           ...  
29526   0.47   8.55   23.30     2.24    12.07    0.73  41.0          Good  
29527   0.52  12.72   30.14     0.74     2.21    0.38  70.0  Satisfactory  
29528   0.48   8.42   30.96     0.01     0.01    0.00  68.0  Satisfactory  
29529   0.52   9.84   28.30     0.00     0.00    0.00  54.0  Satisfactory  
29530   0.59   2.10   17.05      NaN      NaN     NaN  50.0          Good  

[29531 rows x 16 columns]

In [4]:
df.isna()

City   Date  PM2.5   PM10     NO    NO2    NOx    NH3     CO    SO2  \
0      False  False   True   True  False  False  False   True  False  False   
1      False  False   True   True  False  False  False   True  False  False   
2      False  False   True   True  False  False  False   True  False  False   
3      False  False   True   True  False  False  False   True  False  False   
4      False  False   True   True  False  False  False   True  False  False   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
29526  False  False  False  False  False  False  False  False  False  False   
29527  False  False  False  False  False  False  False  False  False  False   
29528  False  False  False  False  False  False  False  False  False  False   
29529  False  False  False  False  False  False  False  False  False  False   
29530  False  False  False  False  False  False  False  False  False  False   

          O3  Benzene  Toluene  Xylene    AQI  AQI_Bucket  
0      False    False    False   False   True        True  
1      False    False    False   False   True        True  
2      False    False    False   False   True        True  
3      False    False    False   False   True        True  
4      False    False    False   False   True        True  
...      ...      ...      ...     ...    ...         ...  
29526  False    False    False   False  False       False  
29527  False    False    False   False  False       False  
29528  False    False    False   False  False       False  
29529  False    False    False   False  False       False  
29530  False     True     True    True  False       False  

[29531 rows x 16 columns]

In [5]:
df.dropna(inplace=True)

In [6]:
df

City        Date  PM2.5    PM10    NO    NO2    NOx    NH3  \
2123       Amaravati  2017-11-25  81.40  124.50  1.44  20.50  12.08  10.72   
2124       Amaravati  2017-11-26  78.32  129.06  1.26  26.00  14.85  10.28   
2125       Amaravati  2017-11-27  88.76  135.32  6.60  30.85  21.77  12.91   
2126       Amaravati  2017-11-28  64.18  104.09  2.56  28.07  17.01  11.42   
2127       Amaravati  2017-11-29  72.47  114.84  5.23  23.20  16.59  12.25   
...              ...         ...    ...     ...   ...    ...    ...    ...   
29525  Visakhapatnam  2020-06-26   7.63   32.27  5.91  23.27  17.19  11.15   
29526  Visakhapatnam  2020-06-27  15.02   50.94  7.68  25.06  19.54  12.47   
29527  Visakhapatnam  2020-06-28  24.38   74.09  3.42  26.06  16.53  11.99   
29528  Visakhapatnam  2020-06-29  22.91   65.73  3.45  29.53  18.33  10.71   
29529  Visakhapatnam  2020-06-30  16.64   49.97  4.05  29.26  18.80  10.03   

         CO    SO2      O3  Benzene  Toluene  Xylene    AQI    AQI_Bucket  
2123   0.12  15.24  127.09     0.20     6.50    0.06  184.0      Moderate  
2124   0.14  26.96  117.44     0.22     7.95    0.08  197.0      Moderate  
2125   0.11  33.59  111.81     0.29     7.63    0.12  198.0      Moderate  
2126   0.09  19.00  138.18     0.17     5.02    0.07  188.0      Moderate  
2127   0.16  10.55  109.74     0.21     4.71    0.08  173.0      Moderate  
...     ...    ...     ...      ...      ...     ...    ...           ...  
29525  0.46   6.87   19.90     1.45     5.37    1.45   47.0          Good  
29526  0.47   8.55   23.30     2.24    12.07    0.73   41.0          Good  
29527  0.52  12.72   30.14     0.74     2.21    0.38   70.0  Satisfactory  
29528  0.48   8.42   30.96     0.01     0.01    0.00   68.0  Satisfactory  
29529  0.52   9.84   28.30     0.00     0.00    0.00   54.0  Satisfactory  

[6236 rows x 16 columns]

In [7]:
df.isna().sum()

City          0
Date          0
PM2.5         0
PM10          0
NO            0
NO2           0
NOx           0
NH3           0
CO            0
SO2           0
O3            0
Benzene       0
Toluene       0
Xylene        0
AQI           0
AQI_Bucket    0
dtype: int64

In [8]:
df = df.drop_duplicates()

In [9]:
df

City        Date  PM2.5    PM10    NO    NO2    NOx    NH3  \
2123       Amaravati  2017-11-25  81.40  124.50  1.44  20.50  12.08  10.72   
2124       Amaravati  2017-11-26  78.32  129.06  1.26  26.00  14.85  10.28   
2125       Amaravati  2017-11-27  88.76  135.32  6.60  30.85  21.77  12.91   
2126       Amaravati  2017-11-28  64.18  104.09  2.56  28.07  17.01  11.42   
2127       Amaravati  2017-11-29  72.47  114.84  5.23  23.20  16.59  12.25   
...              ...         ...    ...     ...   ...    ...    ...    ...   
29525  Visakhapatnam  2020-06-26   7.63   32.27  5.91  23.27  17.19  11.15   
29526  Visakhapatnam  2020-06-27  15.02   50.94  7.68  25.06  19.54  12.47   
29527  Visakhapatnam  2020-06-28  24.38   74.09  3.42  26.06  16.53  11.99   
29528  Visakhapatnam  2020-06-29  22.91   65.73  3.45  29.53  18.33  10.71   
29529  Visakhapatnam  2020-06-30  16.64   49.97  4.05  29.26  18.80  10.03   

         CO    SO2      O3  Benzene  Toluene  Xylene    AQI    AQI_Bucket  
2123   0.12  15.24  127.09     0.20     6.50    0.06  184.0      Moderate  
2124   0.14  26.96  117.44     0.22     7.95    0.08  197.0      Moderate  
2125   0.11  33.59  111.81     0.29     7.63    0.12  198.0      Moderate  
2126   0.09  19.00  138.18     0.17     5.02    0.07  188.0      Moderate  
2127   0.16  10.55  109.74     0.21     4.71    0.08  173.0      Moderate  
...     ...    ...     ...      ...      ...     ...    ...           ...  
29525  0.46   6.87   19.90     1.45     5.37    1.45   47.0          Good  
29526  0.47   8.55   23.30     2.24    12.07    0.73   41.0          Good  
29527  0.52  12.72   30.14     0.74     2.21    0.38   70.0  Satisfactory  
29528  0.48   8.42   30.96     0.01     0.01    0.00   68.0  Satisfactory  
29529  0.52   9.84   28.30     0.00     0.00    0.00   54.0  Satisfactory  

[6236 rows x 16 columns]

In [10]:
pd.DataFrame(df.columns)

0
0         City
1         Date
2        PM2.5
3         PM10
4           NO
5          NO2
6          NOx
7          NH3
8           CO
9          SO2
10          O3
11     Benzene
12     Toluene
13      Xylene
14         AQI
15  AQI_Bucket

In [11]:
df.drop(columns=["City", "Date", "AQI_Bucket"], inplace=True)

In [12]:
df

PM2.5    PM10    NO    NO2    NOx    NH3    CO    SO2      O3  Benzene  \
2123   81.40  124.50  1.44  20.50  12.08  10.72  0.12  15.24  127.09     0.20   
2124   78.32  129.06  1.26  26.00  14.85  10.28  0.14  26.96  117.44     0.22   
2125   88.76  135.32  6.60  30.85  21.77  12.91  0.11  33.59  111.81     0.29   
2126   64.18  104.09  2.56  28.07  17.01  11.42  0.09  19.00  138.18     0.17   
2127   72.47  114.84  5.23  23.20  16.59  12.25  0.16  10.55  109.74     0.21   
...      ...     ...   ...    ...    ...    ...   ...    ...     ...      ...   
29525   7.63   32.27  5.91  23.27  17.19  11.15  0.46   6.87   19.90     1.45   
29526  15.02   50.94  7.68  25.06  19.54  12.47  0.47   8.55   23.30     2.24   
29527  24.38   74.09  3.42  26.06  16.53  11.99  0.52  12.72   30.14     0.74   
29528  22.91   65.73  3.45  29.53  18.33  10.71  0.48   8.42   30.96     0.01   
29529  16.64   49.97  4.05  29.26  18.80  10.03  0.52   9.84   28.30     0.00   

       Toluene  Xylene    AQI  
2123      6.50    0.06  184.0  
2124      7.95    0.08  197.0  
2125      7.63    0.12  198.0  
2126      5.02    0.07  188.0  
2127      4.71    0.08  173.0  
...        ...     ...    ...  
29525     5.37    1.45   47.0  
29526    12.07    0.73   41.0  
29527     2.21    0.38   70.0  
29528     0.01    0.00   68.0  
29529     0.00    0.00   54.0  

[6236 rows x 13 columns]

In [13]:
df.columns

Index(['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3',
       'Benzene', 'Toluene', 'Xylene', 'AQI'],
      dtype='object')

In [14]:
d1 = df.loc[:, ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2']]
d2 = df.loc[:, ['O3','Benzene', 'Toluene', 'Xylene', 'AQI']]

In [15]:
d1

PM2.5    PM10    NO    NO2    NOx    NH3    CO    SO2
2123   81.40  124.50  1.44  20.50  12.08  10.72  0.12  15.24
2124   78.32  129.06  1.26  26.00  14.85  10.28  0.14  26.96
2125   88.76  135.32  6.60  30.85  21.77  12.91  0.11  33.59
2126   64.18  104.09  2.56  28.07  17.01  11.42  0.09  19.00
2127   72.47  114.84  5.23  23.20  16.59  12.25  0.16  10.55
...      ...     ...   ...    ...    ...    ...   ...    ...
29525   7.63   32.27  5.91  23.27  17.19  11.15  0.46   6.87
29526  15.02   50.94  7.68  25.06  19.54  12.47  0.47   8.55
29527  24.38   74.09  3.42  26.06  16.53  11.99  0.52  12.72
29528  22.91   65.73  3.45  29.53  18.33  10.71  0.48   8.42
29529  16.64   49.97  4.05  29.26  18.80  10.03  0.52   9.84

[6236 rows x 8 columns]

In [16]:
d2

O3  Benzene  Toluene  Xylene    AQI
2123   127.09     0.20     6.50    0.06  184.0
2124   117.44     0.22     7.95    0.08  197.0
2125   111.81     0.29     7.63    0.12  198.0
2126   138.18     0.17     5.02    0.07  188.0
2127   109.74     0.21     4.71    0.08  173.0
...       ...      ...      ...     ...    ...
29525   19.90     1.45     5.37    1.45   47.0
29526   23.30     2.24    12.07    0.73   41.0
29527   30.14     0.74     2.21    0.38   70.0
29528   30.96     0.01     0.01    0.00   68.0
29529   28.30     0.00     0.00    0.00   54.0

[6236 rows x 5 columns]

In [17]:
pd.concat([d1, d2], axis=1)

PM2.5    PM10    NO    NO2    NOx    NH3    CO    SO2      O3  Benzene  \
2123   81.40  124.50  1.44  20.50  12.08  10.72  0.12  15.24  127.09     0.20   
2124   78.32  129.06  1.26  26.00  14.85  10.28  0.14  26.96  117.44     0.22   
2125   88.76  135.32  6.60  30.85  21.77  12.91  0.11  33.59  111.81     0.29   
2126   64.18  104.09  2.56  28.07  17.01  11.42  0.09  19.00  138.18     0.17   
2127   72.47  114.84  5.23  23.20  16.59  12.25  0.16  10.55  109.74     0.21   
...      ...     ...   ...    ...    ...    ...   ...    ...     ...      ...   
29525   7.63   32.27  5.91  23.27  17.19  11.15  0.46   6.87   19.90     1.45   
29526  15.02   50.94  7.68  25.06  19.54  12.47  0.47   8.55   23.30     2.24   
29527  24.38   74.09  3.42  26.06  16.53  11.99  0.52  12.72   30.14     0.74   
29528  22.91   65.73  3.45  29.53  18.33  10.71  0.48   8.42   30.96     0.01   
29529  16.64   49.97  4.05  29.26  18.80  10.03  0.52   9.84   28.30     0.00   

       Toluene  Xylene    AQI  
2123      6.50    0.06  184.0  
2124      7.95    0.08  197.0  
2125      7.63    0.12  198.0  
2126      5.02    0.07  188.0  
2127      4.71    0.08  173.0  
...        ...     ...    ...  
29525     5.37    1.45   47.0  
29526    12.07    0.73   41.0  
29527     2.21    0.38   70.0  
29528     0.01    0.00   68.0  
29529     0.00    0.00   54.0  

[6236 rows x 13 columns]

In [18]:
x = df.iloc[:, :-1].to_numpy()

In [19]:
x

array([[8.1400e+01, 1.2450e+02, 1.4400e+00, ..., 2.0000e-01, 6.5000e+00,
        6.0000e-02],
       [7.8320e+01, 1.2906e+02, 1.2600e+00, ..., 2.2000e-01, 7.9500e+00,
        8.0000e-02],
       [8.8760e+01, 1.3532e+02, 6.6000e+00, ..., 2.9000e-01, 7.6300e+00,
        1.2000e-01],
       ...,
       [2.4380e+01, 7.4090e+01, 3.4200e+00, ..., 7.4000e-01, 2.2100e+00,
        3.8000e-01],
       [2.2910e+01, 6.5730e+01, 3.4500e+00, ..., 1.0000e-02, 1.0000e-02,
        0.0000e+00],
       [1.6640e+01, 4.9970e+01, 4.0500e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]])

In [20]:
y = df.iloc[:, -1].to_numpy()

In [21]:
y

array([184., 197., 198., ...,  70.,  68.,  54.])

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [23]:
x_train, x_test, y_train, y_test

(array([[ 30.12,  85.69,  17.86, ...,   1.43,   1.88,   2.  ],
        [ 42.4 , 126.5 ,   5.03, ...,   3.85,   9.11,   2.6 ],
        [ 27.76,  52.71,  14.  , ...,   1.85,   1.11,   2.  ],
        ...,
        [ 78.61, 145.1 ,  13.  , ...,   3.3 ,   8.08,   2.19],
        [117.98, 145.85,  26.65, ...,   3.49,  22.67,   0.19],
        [ 43.19,  94.4 ,   4.42, ...,   1.5 ,  12.68,   0.27]]),
 array([[2.0997e+02, 3.3091e+02, 8.9410e+01, ..., 5.9700e+00, 3.6870e+01,
         1.3600e+00],
        [1.0460e+01, 2.5570e+01, 3.8400e+00, ..., 1.1900e+00, 5.3900e+00,
         3.1000e-01],
        [3.2780e+01, 5.8330e+01, 1.5570e+01, ..., 1.5260e+01, 1.2280e+01,
         3.8700e+00],
        ...,
        [3.3620e+01, 6.0660e+01, 2.5000e+00, ..., 3.2000e-01, 6.1000e-01,
         1.2000e-01],
        [6.0700e+01, 8.1890e+01, 2.0760e+01, ..., 9.1000e-01, 7.6800e+00,
         1.7500e+00],
        [5.7280e+01, 1.2583e+02, 9.0200e+00, ..., 5.7700e+00, 1.0270e+01,
         2.7000e+00]]),
 array([ 78., 11

In [24]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [25]:
regressor.intercept_

15.37072469673177

In [26]:
regressor.coef_

array([ 0.88125907,  0.41497664, -0.11913121, -0.19448708,  0.41592062,
        0.02261085,  7.60834257, -0.01084627,  0.29945754, -0.21389376,
       -0.24762241, -0.22929309])

In [27]:
y_train_pred = regressor.predict(x_train)

In [28]:
y_train_pred

array([ 99.52147202, 118.44507526,  83.96957693, ..., 224.51551141,
       196.32060126, 116.45844096])

In [29]:
pd.DataFrame(pd.Series(y_train_pred), pd.Series(y_train))

0
78.0    75.758796
112.0  118.712324
97.0   421.210958
132.0  239.092301
175.0  128.549869
...           ...
220.0   95.104584
236.0   97.622671
234.0  111.980431
281.0  167.799756
122.0  203.019835

[4988 rows x 1 columns]

In [30]:
from sklearn.metrics import mean_squared_error, r2_score

pred = regressor.predict(x_train)

r2_score((y_train), (pred))


0.911505265642307

In [31]:
mean_squared_error((y_train), (pred))

741.1670538407143

In [32]:
mean_squared_error((y_train), (pred), squared=False)

27.224383442802047

In [33]:
from sklearn.metrics import mean_squared_error, r2_score

pred = regressor.predict(x_test)

print('train mse: {}'.format(
    mean_squared_error((y_test), (pred))))
print('train rmse: {}'.format(
    mean_squared_error((y_test), (pred), squared=False)))
print('train r2: {}'.format(
    r2_score((y_test), (pred))))
print()

train mse: 850.5728998808004
train rmse: 29.16458297114499
train r2: 0.9102378339668145



In [36]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(x)
x = ss.transform(x)

In [37]:
x

array([[ 0.37375467,  0.01260924, -0.7773514 , ..., -0.69153128,
        -0.31121784, -0.55074012],
       [ 0.31640473,  0.06576563, -0.78633513, ..., -0.68758008,
        -0.19319961, -0.54632968],
       [ 0.51079868,  0.13873909, -0.51981791, ..., -0.67375088,
        -0.21924501, -0.53750881],
       ...,
       [-0.68796401, -0.57502528, -0.67853041, ..., -0.58484888,
        -0.66038901, -0.4801731 ],
       [-0.71533557, -0.67247866, -0.67703313, ..., -0.72906768,
        -0.83945115, -0.56397144],
       [-0.83208366, -0.85619459, -0.64708737, ..., -0.73104328,
        -0.84026507, -0.56397144]])